import { AuthContextProvider } from '@/context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'
import classNames from 'classnames'

const inter = Inter({ display: 'swap', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={classNames({ [inter.className]: true, 'bg-gray-50': true })}>
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  )
}
